# Basic Information 
title: Antoine de Mathelin
position: Ph.D. Student
affiliation: Centre Borelli, ENS Paris-Saclay
affiliation_link: https://centreborelli.ens-paris-saclay.fr/en
affiliation_logo: ./assets/img/logo.webp
email: antoine.de_mathelin (at) ens-paris-saclay.fr

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: antoine de mathelin
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=h79bffAAAAAJ&hl=fr&oi=ao
github_link: https://github.com/antoinedemathelin

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: false

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
